config/routes.rb
Rails.application.routes.draw do

    
  root 'homepage#home'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'show'    => 'user#show'
  get    'edit'    => 'user#edit'
  
  get    'order'        => 'workorders#new'
  post   'order'        => 'workorders#create'
  
  get    'area'        => 'serviceareas#new'
  post   'area'        => 'serviceareas#create'
  
  resources :users
  resources :workorders
  resources :serviceareas
  resources :resources
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/views/layouts/_header.html.erb
<div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
    <div class="container-fluid">
        <div class="navbar-header"><a class="navbar-brand" href="/">MOVESHER</a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder">
                <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span>
                <span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse navbar-menubuilder">
            <ul class="nav navbar-nav navbar-left">
                <li><%= link_to "REQUEST SERVICE", order_path, method: "get", :class=>"user-titles" %>
                </li>
                <li><%= link_to "MOVER", area_path, method: "get", :class=>"user-titles" %>
                </li>
            </ul>
            <div class="nav navbar-nav navbar-right">
                <li><a href="/" class="menu-links">HELP</a></li>
                <% if logged_in?  %>
                    <li><%= link_to "Log Out", logout_path, method: "delete", :class=>"menu-links" %></li>
                <% else %>
                    <li><a href="/login" class="menu-links">LOGIN IN</a></li>
                <% end %>
                <li><a href="/signup" class="menu-button">BECOME A MOVER</a></li>
            </div> 
        </div>    
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <title>MOVESHER</title>
 
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css?body=1">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  
  <%= yield %>
  
  <!--
  <div class="is-centered">
  <% flash.each do |message_type, message| %>
  <div class="column notification is-<%= message_type %>"><%= message %></div>
  <% end %>
  </div>
  -->
  
 <!--
  <%= debug(params) if Rails.env.development? %>
  -->
  
</body>
</html>